### PR TITLE
Accessibility updates based on internal report findings

### PR DESCRIPTION
**Pull request by cruddasj**
## Description

[Goes here]

## Todo's before PR

- [ ] Rebase from develop
- [ ] Unit tests passed (`make test`)
- [ ] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [ ] PR description describes the overall goals of PR commits
- [ ] Templates been checked with relevant user-story

## Migrations

- [ ] Null fields in models specifies default value
- [ ] You generated and applied migrations (`make migrate`)
- [ ] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [ ] Specified reviewers (even if it's yourself)
- [ ] Specified assigneses (those who'll merge)
- [ ] Specified labels
- [ ] Specified milestone

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by cruddasj** [comment]
@GeevesH-IS - would you please be able to merge the latest develop branch into this PR? The checks are currently failing from what looks like the DOB field updates (which were since resolved)?

**Comment by GeevesH-IS** [comment]
rerun jenkins build

**Comment by GeevesH-IS** [comment]
@cruddasj , that's true for the summary pages, but it looks like this is failing when it's going back to the task list, where the task name is still a tr. Also, on the most current build, the search timed out on the wait.

**Comment by GeevesH-IS** [comment]
Hi @cruddasj , I've reverted this branch to the state where the build passes, so that we may merge this and correct the code to a better practice after the show & tell if needed. For now I'd like to prioritise CCN3-749 as I can't get Selenium tests working locally (I'll look at this further before ceremonies tomorrow morning), so that both tickets are in a state to be put on accept. Let me know if you'd like me to prioritse differently.

**Comment by GeevesH-IS** [comment]
rerun jenkins build

**Pull request merged**
