### PR TITLE
Merge/sprint 16 feature merge

### PR DESCRIPTION
**Pull request by cruddasj**
## Description

Merge down of features introduced in Sprint 16. A single merge is being made here to preserve EC2 CPU credits.

## Todo's before PR

- [x] Branch has been rebased against develop
- [x] Unit tests passed (`make test`)
- [x] PR named appropriately - see [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [x] Templates have been checked against the relevant user-story

## Migrations

- [ ] Null fields in models specifies default value
- [ ] You generated and applied migrations (`make migrate`)
- [ ] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [ ] Specified reviewers (even if it's yourself)
- [x] Specified assignees (those who'll merge)
- [x] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [ ] Should be rebased?
- [x] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by cruddasj** [comment]
re-run jenkins build

**Comment by Thomas-95IS** [comment]
Running local Selenium tests for this now.

**Comment by ricaduchateau** [comment]
@Thomas-95IS one test failing (accessing people in home task after completion) - will fix

**Comment by cruddasj** [comment]
@ricaduchateau - can you please commit straight into this PR branch when you have a fix for the selenium test and drop a short comment to let us know?

**Comment by ricaduchateau** [comment]
Hi @cruddasj, will do

**Comment by ricaduchateau** [comment]
Hi @cruddasj @Thomas-95IS @kingainformed I've fixed a broken if statement that was causing test_task_summaries_display_on_completion to fail

**Pull request merged**
