### PR TITLE
Refactor/forms

### PR DESCRIPTION
**Pull request by matthewstyles**
## Description
Simply split childminder forms out, and moved the security question and magic link views to the views directory.

NB: this commit also includes the update email commits, so tread carefully.
## Todo's before PR

- [x] Rebase from develop
- [x] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [x] Templates been checked with relevant user-story

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assigneses (those who'll merge)
- [x] Specified labels
- [x] Specified milestone

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [x] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by cruddasj** [comment]
@matthewstyles - can you please rebase against develop?

**Comment by matthewstyles** [comment]
@cruddasj navigation headers commit is now merged in

**Comment by cruddasj** [comment]
@GeevesH-IS - would you please be able to look at this PR this morning?

**Comment by GeevesH-IS** [comment]
@cruddasj - will do, I'll start shortly

**Pull request merged**
